// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MovieCollectionContext))]
    [Migration("20230208062743_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission6.Models.MovieFormResponse", b =>
                {
                    b.Property<int>("RentalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RentalID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            RentalID = 1,
                            Category = "Suspense",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Notes = "My favorite movie!",
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = "2010"
                        },
                        new
                        {
                            RentalID = 2,
                            Category = "Action",
                            Director = "Kevin Feige",
                            Edited = false,
                            Notes = "Avengers are the best!",
                            Rating = "PG-13",
                            Title = "Age of Ultron",
                            Year = "2015"
                        },
                        new
                        {
                            RentalID = 3,
                            Category = "Musical",
                            Director = "Disney",
                            Edited = false,
                            Notes = "The best ending!",
                            Rating = "PG",
                            Title = "High School Musical 3: Senior Year",
                            Year = "2008"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
